updated citylearn installation to versioned release, figure reference
climatechange-ai-tutorials/citylearn pull request #2
Opened 2024-06-09 16:56 UTC by kingsleynweye

updated citylearn installation to versioned release, figure references to CityLearn master branch and text refactoring.

2024-06-10 15:46 UTC, mdhanna requested changes
Ideally the notebook should run end-to-end even if the exercises are not complete. I see there is a dependency under the CityLearn Tabular Q-Learning Implementation section where `random_env` was defined in Exercise 1.  Would you mind commenting out lines 10 in that cell, maybe with an instruction to uncomment them if Exercise 1 is complete? There are a couple additional references to `random_env` under Experiment 4.

2024-06-11 11:10 UTC, kingsleynweye commented
> Ideally the notebook should run end-to-end even if the exercises are not complete. I see there is a dependency under the CityLearn Tabular Q-Learning Implementation section where `random_env` was defined in Exercise 1. Would you mind commenting out lines 10 in that cell, maybe with an instruction to uncomment them if Exercise 1 is complete? There are a couple additional references to `random_env` under Experiment 4.

I have commented out `random_env` with instructions to uncomment if Exercise 1 has been completed.

2024-06-11 13:30 UTC, mdhanna commented
Thank you!

2024-06-11 13:31 UTC, mdhanna approved these changes

2024-06-11 13:31 UTC, merged